spring:
  application:
    name: seckill-engine
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    sentinel:
      eager: false
      enabled: false
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.NacosDiscoveryAutoConfiguration
      - com.alibaba.cloud.nacos.NacosServiceAutoConfiguration
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
      - com.alibaba.cloud.sentinel.SentinelAutoConfiguration
      - org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration

server:
  port: 11020

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true

logging:
  level:
    com.seckill: DEBUG
