spring:
  application:
    name: seckill-engine
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    sentinel:
      eager: false
      enabled: false
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.NacosDiscoveryAutoConfiguration
      - com.alibaba.cloud.nacos.NacosServiceAutoConfiguration
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - com.alibaba.cloud.sentinel.SentinelAutoConfiguration
      - org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration

server:
  port: 11020

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true

logging:
  level:
    com.seckill: DEBUG
